[package]
name = "send-message"
version = "0.1.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[[bin]]
name = "send-message"
path = "send-message.rs"

[dependencies]
scan-rules = "0.1.1"
winapi = "0.2.5"
wui = { version = "0.1.0", path = "../../" }
